name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install xcb
      run:   |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt install xcb
                  sudo apt install libxcb1
                  sudo apt install libxcb1-dev
             fi
      shell: bash

    - name: Build
      run: cd kicad-wakatime && cargo build --release

    - uses: actions/upload-artifact@v4
      with:
        name: kicad-wakatime-${{ matrix.os }}
        path: ${{ github.workspace }}/kicad-wakatime/target/release/kicad-wakatime*

